[build]
  publish = "dist"  # Make sure this matches the output directory in Vite
  command = "npm run build"  # This will be triggered by Netlify during the deployment

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200
  force = true