
[build]
  publish = "dist"  # Make sure this matches the output directory in Vite
  command = "npm run build"  # This will be triggered by Netlify during the deployment

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/json"
